<a href="https://colab.research.google.com/github/piyushagarwal08/Adhoc-Specialisation-ML/blob/master/Adhoc_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


# **BASICS OF NUMPY**

## Slicing and Indexing

In [0]:
a = np.array([2,7,1,99,4])

In [5]:
type(a)

numpy.ndarray

In [0]:
b = np.array([12,17,199,11,14])

In [7]:
b[0]

12

In [8]:
a[0]
#print 0 index position of a array

2

In [9]:
a+b
#Add two different arrays at index positions

array([ 14,  24, 200, 110,  18])

In [12]:
a+7
#Add 7 with all numbers in list

array([  9,  14,   8, 106,  11])

In [13]:
a*2
#Multiply each element with 2

array([  4,  14,   2, 198,   8])

In [0]:
c = np.array([1,2,3])

In [18]:
c+b
#can not apply any mathematical operator on array with different length

ValueError: ignored

In [0]:
x = np.array([[2,5,8],[3,6,4]])
# [[C1,C2,C3],[C1,C2,C3]] or [[R1],[R2]] no of columns in a array should be same for all rows

In [22]:
x
# 2D array [2x3]Matrix

array([[2, 5, 8],
       [3, 6, 4]])

In [25]:
x[1,2]
#
#           C1   C2  C3
#       R1  0,0  0,1 0,2
#       R2  1,0  1,1 1,2

4

In [0]:
y=x+3
# add 3 to all numbers in 2D array

In [27]:
y

array([[ 5,  8, 11],
       [ 6,  9,  7]])

In [28]:
z = np.array([[2,7],[3,8],[2,9],[9,2]])
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [29]:
z.shape
# Tells (number of rows,no of columns) in an array

(4, 2)

In [31]:
z[0:2]
# prints selective row or range of row

array([[2, 7],
       [3, 8]])

In [34]:
z[0:2,0]
# in numpy , variable[Row-Range,Column-Range]

array([2, 3])

In [37]:
y[0:,1]
# to get 2nd column of array y

array([8, 9])

In [38]:
y

array([[ 5,  8, 11],
       [ 6,  9,  7]])

In [39]:
y[0:,[0,2]]
# to get all rows and column at 0 index and at 2 index, used to get any column randomly

array([[ 5, 11],
       [ 6,  7]])

In [40]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [0]:

#         C0    C1      C2
#      R0 1      9       7
#      R1 3      2       8
#      R2 4      5       6
#      R3 2      9       0
a = np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])

In [52]:
a

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [56]:
a[1:4,-1]

array([8, 6, 0])

In [58]:
a[1:,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [59]:
a.reshape(4,3)

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [60]:
a.reshape(3,4)
# used to change the matrix or array order of predefined array

array([[1, 9, 7, 3],
       [2, 8, 4, 5],
       [6, 2, 9, 0]])

In [61]:
a.transpose()


array([[1, 3, 4, 2],
       [9, 2, 5, 9],
       [7, 8, 6, 0]])

#  TASK
  1. take rows and column input from user and calculate how many rows and column combination are possible, factor of each number and find all possible array combination 
  2. Generate 3x2 and 2x5  2D array with random element and save this data into two seperate files and print the data
  3. Revise numpy and matplotlib
  4. revise requests module

In [66]:
np.zeros((3,6),dtype=int)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [67]:
np.ones((5,2))
# by default it takes float values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
# array of 4,5 with all 9's
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [73]:
'''for i in dir(np):
  if 'zer' in i:
    print(i)
'''    
[i for i in dir(np) if 'zer' in i]

['count_nonzero',
 'flatnonzero',
 'nonzero',
 'trim_zeros',
 'zeros',
 'zeros_like']

# DATA PROCESSING and VISUALIZATION