<a href="https://colab.research.google.com/github/piyushagarwal08/Adhoc-Specialisation-ML/blob/DeepLearning/DL_DAY13_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
# to assign fix value in tensorflow , we need to define constant
x = tf.constant([420,440])# multivalue constant
x1 = tf.constant(420)

In [3]:
x,x1

(<tf.Tensor 'Const:0' shape=(2,) dtype=int32>,
 <tf.Tensor 'Const_1:0' shape=() dtype=int32>)

In [4]:
# type of x
type(x)

tensorflow.python.framework.ops.Tensor

In [0]:
# making another tensor
y = tf.constant(20)

In [0]:
# making an equation, forming a new tensorflow
z = x+y    # compile the equation and store in z and wait for resources such as GPU/CPU/TPU
z1 = tf.add(x,y)   # adding x and y

In [0]:
# now time for assigning resources to our equation
sess = tf.Session()  # connect CPU or GPU or TPU

In [0]:
# now we can run our equation
output = sess.run(z)

In [9]:
output

array([440, 460], dtype=int32)

In [0]:
sess.close()

In [12]:
output1

array([440, 460], dtype=int32)

In [0]:
# we can perform same task in another way where no need to close seesion
with tf.Session() as sas:
  output1=sas.run(z)
  tf.summary.FileWriter('graph',sas.graph)

# PLACEHOLDER

In [0]:
# first place holder
p1=tf.placeholder(tf.int32)

In [0]:
# placeholder second
p2=tf.placeholder(tf.int32)

In [0]:
# adding values
sum = tf.add(p1,p2)

In [0]:
# or adding as
sum1 = p1 + p2

In [0]:
# time for creating session
with tf.Session() as sess:
  output2=sess.run(sum1,{p1:[3,6,1,5],p2:[6,2,0,3]})

In [27]:
output2

array([9, 8, 1, 8], dtype=int32)